name: Client CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Use NodeJS ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: install dependencies
      run: npm ci # How is npm i different from npm ci
    
    - name: Generate build
      run: CI=false NODE_ENV=development npm run build --if-present

    - name: Deploy to netlify
      uses: South-Paw/action-netlify-deploy@v1.2.0  #this will do everything to set up the netlify cli on the server
      env: 
        NODE_ENV: development
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
        build-dir: './build'
        comment-on-commit: true

# In github actions anything under "jobs" is carried out concurrently or parallely..to make it sychronous we need to use "needs" keyword