name: Client CI
on:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Use NodeJS 12x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: install dependencies
      run: npm i
    
    - name: Generate build
      run: npm run build --if-present

    - name: Deploy to netlify
      uses: South-Paw/action-netlify-deploy@v1.2.0
      env:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}